"""Generate Unicode 15.0.0 search mappings with Python 3.12 (no dependencies).

Source: https://www.unicode.org/Public/15.0.0/ucd/
Algorithm: https://www.unicode.org/reports/tr15/
Unicode data license: https://www.unicode.org/license.txt
Run dart format on the output afterwards. Hangul is handled algorithmically.
"""

from pathlib import Path
import unicodedata

assert unicodedata.unidata_version == "15.0.0", "Use Python 3.12 / Unicode 15.0.0"
target = Path(__file__).resolve().parents[1] / "lib/app/data/sqlite/concept_search_key.g.dart"
lines = [
    "// Generated by scripts/generate-concept-search-key.py; do not edit.",
    "// Unicode 15.0.0; https://www.unicode.org/license.txt",
    "part of 'concept_search_key.dart';",
    "",
    "const _searchMappings = <int, String>{",
]
for codepoint in range(0x110000):
    if 0xAC00 <= codepoint <= 0xD7A3 or 0xD800 <= codepoint <= 0xDFFF:
        continue
    original = chr(codepoint)
    key = "".join(
        char for char in unicodedata.normalize("NFD", original)
        if not unicodedata.category(char).startswith("M")
    ).casefold()
    if key != original:
        escaped = "".join(f"\\u{{{ord(char):x}}}" for char in key)
        lines.append(f"  0x{codepoint:x}: '{escaped}',")
lines.append("};")
target.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"Generated {target.name}: {len(lines) - 6} mappings")
